// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        int32
	ApiKey    string
	UserID    string
	CreatedAt pgtype.Timestamp
}
