// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	DeleteByApiKey(ctx context.Context, apikey string) error
	DeleteByUser(ctx context.Context, userid string) error
	DeleteByUserAndApiKey(ctx context.Context, userid string) error
	GetApiKeys(ctx context.Context) ([]ApiKey, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error
}

var _ Querier = (*Queries)(nil)
